title: Study on High School Exam Pass Rates – Analysis for Poland in the Years 2012-2024
--logo: /assets/img/headshot_circle.png
--#description: Nursuries for Children - Market Research for Poland in 2025
theme: jekyll-theme-minimal
minimal:
  show_repo_link: false
  show_downloads: false
  search: false
  skin: auto
plugins:
  - jekyll-feed
include: ["assets/css"]
classes: wide
